package org.pathlab.forge.model;

public enum JobState {
    PENDING,
    INSPECTING,
    NEEDS_REVIEW,
    READY,
    EXPORTING_OME,
    VALIDATING_OME,
    GENERATING_DZI,
    VALIDATING_DZI,
    PACKAGING,
    READY_TO_UPLOAD,
    UPLOADING,
    SERVER_PROCESSING,
    READY_PRIVATE,
    PUBLISHED,
    PAUSED,
    CANCEL_REQUESTED,
    CANCELLED,
    FAILED_RETRYABLE,
    FAILED_PERMANENT,
    SKIPPED
}
